### ISSUE TITLE
@load_adult changes current directory

### ISSUE THREAD

**Issue by gpucce** [ashryaagr/Fairness.jl#72]
Hi I don't know if this is a known issue, but using @load_adult appears to be changing the working directory.

```julia
julia> using Fairness

julia> pwd()
"/home/orefici/Repos/CItA_experiments/CItA_XAI"

julia> X, y = @load_adult;

julia> pwd()
"/home/orefici/.julia/packages/Fairness/1mEPa/data"
```

If the issue is real I'd be happy to try and help with a PR if you can point me to where I should look to fix it.

**Comment by ashryaagr** [comment]
Thanks a lot for pointing this out!
I checked, and yes, the issue is real.

 You can look at the definition for `@load_adult` macro [here](https://github.com/ashryaagr/Fairness.jl/blob/master/src/datasets/datasets.jl#L92) . The issue is probably because directory is changed in the `ensure_download` function [here](https://github.com/ashryaagr/Fairness.jl/blob/master/src/datasets/datasets.jl#L24)

Thanks again!
